### ISSUE TITLE
Change path to MP3 bootsound

### ISSUE THREAD

**Issue by shadow2560** [KranKRival/BootSoundNX#1]
I think that the path to the bootsound should be changed to "sdmc:///config/BootSoundNX/bootsound.mp3" because the "bootloader" folder is used by Hekate and I think it was not a good idea to use this folder for the module. Also, the type of path that I propose is used by a lot of modules and I think it's a good thing to "normalize" this type of path.

**Comment by KranKRival** [comment]
next release will have that path :) 

besides it will support .ini so everyone can change the path to desired one 

ill keep the request open for now
thank you.

**Comment by shadow2560** [comment]
Good point for the ini file. An other little thing (I don't want to open an other issue for this), the MAKEFILE have a problem because the module is not compiled as a sysmodule, in the actual config of the project you should add the line "CONFIG_JSON	:=	sysmodule.json" to compile it (you could also rename the "sysmodule.json" file to "config.json" or "BootSoundNX.json" to have the same result).

**Comment by KranKRival** [comment]
oh i just forgot to rename the json  ^^

**Comment by KranKRival** [comment]
sorry for the delay with this , as i have many projects and kinda limited free time , ill take care of this today or max at the week end

**Comment by shadow2560** [comment]
No problem, take your time, it's not like it's a big issue and I have already made my own compilation with a temporary change for the path of the MP3 file.

**Comment by fennectech** [comment]
ane new issues with kosmos toolbox i found

**Comment by KranKRival** [comment]
fixed all addressed issues , thank you guys :) 

please check v1.1.0 release notes there is all the info.

Closed !
