### ISSUE TITLE
10.0.X not supported

### ISSUE THREAD

**Issue by Slluxx** [KranKRival/BootSoundNX#4]
as the title says

**Comment by GameSpate** [comment]
Same here. Any fixes? I don't think BSNX is maintained anymore... :(

**Comment by carcaschoi** [comment]
change titles to contents

**Comment by impeeza** [comment]
Duplicated [https://github.com/KranKRival/BootSoundNX/issues/6#issue-860631923](https://github.com/KranKRival/BootSoundNX/issues/6#issue-860631923) the problem isn't firmware but the new Atmosphère needs the homebrew compiled using the newest tools

**Comment by lol2232** [comment]
> Duplicated [#6 (comment)](https://github.com/KranKRival/BootSoundNX/issues/6#issue-860631923) the problem isn't firmware but the new Atmosphère needs the homebrew compiled using the newest tools

how do you recompile it ? do i just download the source and compile myself or is there other steps

**Comment by impeeza** [comment]
That's correct

**Comment by lol2232** [comment]
> That's correct

im getting some errors trying to compile it do you think you could help

**Comment by lol2232** [comment]
> That's correct

i cannot seem to figure this out it's some weird include issue do you think you could compile it for me

**Comment by impeeza** [comment]
For support go to the proper channels, tjus is only to reporting bugs

**Comment by lol2232** [comment]
> For support go to the proper channels, tjus is only to reporting bugs

do you think you could link the channels your talking about i cant find anything

**Comment by impeeza** [comment]
Gbatemp.net, discord, etc.

**Comment by EmmmaTech** [comment]
> Duplicated [#6 (comment)](https://github.com/KranKRival/BootSoundNX/issues/6#issue-860631923) the problem isn't firmware but the new Atmosphère needs the homebrew compiled using the newest tools

That's not all. Some of the code seems to be outdated, so it needs to be updated.

**Comment by TheModdersDen** [comment]
https://github.com/KranKRival/BootSoundNX/issues/6#issuecomment-895568957
Tada!
